name: Python CI

on:
  [ push, pull_request ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python: [ 3.7, 3.9]
        khulnasoft-version:
          - "8.1"
          - "8.2"
          - "latest"
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker-compose
        run: KHULNASOFT_VERSION=${{matrix.khulnasoft-version}} docker-compose up -d

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Test Execution
        run: tox -e py
  fossa-scan:
    uses: khulnasoft/oss-scanning-public/.github/workflows/oss-scan.yml@main
    secrets: inherit